.github/workflows/ci.yml
.github/workflows/lint.yml
sw/banshee/Makefile

Properly build and test Banshee as part of the CI flow.

ci: Add banshee

---

hw/system/snitch_cluster/Makefile

snitch_cluster: Run Modelsim in 64-bit mode

---

sw/banshee/src/tran.rs

This fixes a Banshee binary translation issue regarding FREP wherein the generated LLVM IR may (through branches or jumps into a loop body) access an SSA value before assignment, leading to an corresponding use domination error on translation.

banshee: Allocate FREP max repetition count to prevent IR use domination

---

sw/banshee/src/engine.rs

The `exit_code` register is initialized to 0 in Banshee. If Banshee stops before writing a return value, it will look as if the execution was successful. This patch checks the LSB of the `exit_code` to make sure the return value was actually written. If we have debug prints enabled, it will generate a warning, otherwise, it will just set Banshee's return value to 1.

banshee: Check if return value was written at all

---

sw/snRuntime/include/snrt.h

This small fix is needed if you want to compile with C++, instead of C.

Updated snrt.h so that it compiles with c++

---

sw/banshee/src/engine.rs

Does what it says in the title ;)

banshee: Add minstret CSR support

---

hw/vendor/patches/pulp_platform_common_cells/0003-vendor-VCS-patches.patch
hw/vendor/pulp_platform_common_cells.lock.hjson
hw/vendor/pulp_platform_common_cells/.github/workflows/ci.yml
hw/vendor/pulp_platform_common_cells/Bender.yml
hw/vendor/pulp_platform_common_cells/CHANGELOG.md
hw/vendor/pulp_platform_common_cells/README.md
hw/vendor/pulp_platform_common_cells/common_cells.core
hw/vendor/pulp_platform_common_cells/include/common_cells/assertions.svh
hw/vendor/pulp_platform_common_cells/include/common_cells/registers.svh
hw/vendor/pulp_platform_common_cells/src/addr_decode.sv
hw/vendor/pulp_platform_common_cells/src/id_queue.sv
hw/vendor/pulp_platform_common_cells/src/rr_arb_tree.sv
hw/vendor/pulp_platform_common_cells/src/stream_fork.sv
hw/vendor/pulp_platform_common_cells/src/stream_mux.sv
hw/vendor/pulp_platform_common_cells/test/addr_decode_tb.sv
hw/vendor/pulp_platform_common_cells/test/cb_filter_tb.sv
hw/vendor/pulp_platform_common_cells/test/fifo_tb.sv
hw/vendor/pulp_platform_common_cells/test/graycode_tb.sv
hw/vendor/pulp_platform_common_cells/test/id_queue_tb.sv
hw/vendor/pulp_platform_common_cells/test/popcount_tb.sv
hw/vendor/pulp_platform_common_cells/test/rr_arb_tree_tb.sv
hw/vendor/pulp_platform_common_cells/test/stream_omega_net_tb.sv
hw/vendor/pulp_platform_common_cells/test/stream_to_mem_tb.sv
hw/vendor/pulp_platform_common_cells/test/stream_xbar_tb.sv
hw/vendor/pulp_platform_common_cells/test/sub_per_hash_tb.sv

That includes the latest changes on the `registers.svh`.

Bump `common_cells` to 6e07bd7

---

hw/system/occamy/src/occamy_pkg.sv
hw/system/occamy/src/occamy_pkg.sv.tpl
hw/system/occamy/src/occamy_top.sv
hw/system/occamy/src/occamy_top.sv.tpl
util/occamygen.py

- Add chip_reg to interconnect
- Followed @niwis' changes from 9af965f to add APB for HBI control to interconnect

Add HBI for Occamy

---

.github/CODEOWNERS
hw/ip/snitch_ssr/src/snitch_ssr.sv
hw/ip/snitch_ssr/src/snitch_ssr_addr_gen.sv

I was running the code through DC and apparently, it has problems with the following lines. I remember @paulsc96 telling me something similar the other day. Can you have a look at whether this is aligned with your expectations?

ssr: DC compatibility fixes

---

hw/ip/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral.sv

Fixes some bugs for configuring the snitch cluster peripheral performance counters.

Fix: peripheral counters

---

hw/system/snitch_cluster/wave/all_cores.do
util/licence-checker.hjson

Adds a simple wave-file to the `snitch_cluster` system

sim: Add universal wave file

---

hw/vendor/openhwgroup_cva6/Bender.yml
hw/vendor/patches/openhwgroup_cva6/0002-cva6-Custom-Bender.yml.patch

Fixes issue where bender fails to find correct path for the `reqrsp_interface` ip.

vendor: Fix reqrsp_interface dependency

---

hw/ip/snitch_ssr/src/snitch_ssr_indirector.sv
hw/ip/snitch_ssr/src/snitch_ssr_intersector.sv
hw/ip/snitch_ssr/src/snitch_ssr_streamer.sv
hw/ip/snitch_ssr/src/snitch_ssr_switch.sv

This fixes some small functional and lint issues found in the SSR RTL during synthesis.

ssr: Synthesis issue and lint fixes

---

hw/system/occamy/src/occamy_pkg.sv
hw/system/occamy/src/occamy_top.sv
hw/system/occamy/src/occamy_top.sv.tpl
util/occamygen.py
util/solder/solder.axi_lite_to_axi.sv.tpl

occamy: Create AXI Lite to AXI connection

---

.github/workflows/publish-docs.yml
docs/doxybook2.json

Fixes an URL bug, **should** work now :D

doc: Fix baseURL in doxybook2 for gh-pages

---

util/container/Dockerfile

Untested, but I guess we will see as soon as we merge.

Docker: Update from `snitch-llvm` to `pulp-llvm`

---

util/container/Dockerfile

Docker: Fix llvm binary name

---

hw/vendor/openhwgroup_cva6/src/cache_subsystem/cache_ctrl.sv
hw/vendor/openhwgroup_cva6/src/cache_subsystem/std_cache_subsystem.sv
hw/vendor/openhwgroup_cva6/src/cache_subsystem/std_nbdcache.sv
hw/vendor/openhwgroup_cva6/src/cache_subsystem/std_no_dcache.sv
hw/vendor/patches/openhwgroup_cva6/0013-ariane-wb-Check-cacheable-region-length.patch

Check the cacheable region's length in Ariane's write-back cache. @fischeti could you check whether this resolves your issue?

ariane/wb: Check cacheable region length

---

hw/ip/future/src/axi_id_remap.sv

Atomic swap operation (amoswap) requests on the AW channel (which have both write and read effects) are prioritized over requests on the AR channel. If a constant stream of amoswaps is present, this can stall the AR channel indefinitely possibly creating the conditions for a deadlock. 
This PR implements a very simple but fairer arbitration mechanism.

axi: Fix `axi_id_remap` prioritizing ATOPs over AR channel

---

hw/vendor/openhwgroup_cva6/src/csr_regfile.sv
hw/vendor/patches/openhwgroup_cva6/0016-Mask-non-enabled-interrupts-in-WFI-control.patch

Integrate upstream changes from PR https://github.com/openhwgroup/cva6/pull/765.

cva6: Patch with upstream changes on WFI

---

sw/snRuntime/include/snrt.h

Add implementation of a test-and-test-and-set lock to snRuntime.

snRuntime: Add test-and-test-and-set lock

---

sw/banshee/src/engine.rs

This fix enables access to external TCDM memories via the slow-path in Banshee. Currently, it will only work for homogeneous configurations where the cores have the same address map. An overhaul of the configuration system is necessary to extend this.

banshee: Allow access to external TCDM via slow-path

---

hw/ip/snitch_cluster/src/snitch_sequencer.sv
hw/ip/snitch_ssr/src/snitch_ssr.sv
hw/ip/snitch_ssr/src/snitch_ssr_addr_gen.sv
hw/ip/snitch_ssr/src/snitch_ssr_credit_counter.sv
hw/ip/snitch_ssr/src/snitch_ssr_indirector.sv
hw/ip/snitch_ssr/test/fixture_ssr_streamer.sv

* Edge case fixes and performance improvements to SSR intersection mechanism
* Fixes to related stream control interface
* Rename credit counter interface to better reflect functionality

ssr: Fixes and improvements to intersection features

---

hw/ip/snitch_ssr/src/snitch_ssr.sv
hw/ip/snitch_ssr/src/snitch_ssr_addr_gen.sv
hw/ip/snitch_ssr/src/snitch_ssr_credit_counter.sv
hw/ip/snitch_ssr/src/snitch_ssr_indirector.sv
util/gen_trace.py

* Slave SSR: Revise intersection counting mechanism to avoid writeback latency
* SSR: Enforce flush of inflight requests when direction is reversed between jobs
* Master SSR: Fix default values for zero FIFO `zero_empty` when not instantiated
* Tracer: fix handling of performance metrics derived from unmeasured metrics

ssr: Revise intersection counting, edge case fixes

---

util/addrmapgen.py

add support to generate the addressmap (pdf and md) for occamy configurations with a different amount of clusters than 4

addrmapgen: Make `nr_clusters` configurable

---

sw/applications/src/kernels/conv2d.c

The changes in #341 added backpressure to SSR config writes. This PR fixes some of the SSR configuration in the kernels that were blocking because the previous SSR stream was not consumed entirely

sw: Fix stalling SSR configuration write

---

hw/vendor/lowrisc_opentitan/spi_host/rtl/spi_host_fsm.sv
hw/vendor/patches/lowrisc_opentitan/spi_host/0004-spi_host-More-fixes-390-393.patch

spi-host: Fix outstanding issues

---

hw/vendor/patches/pulp_platform_fpnew/0001-fpnew-fix-modelsim-issue-with-reduced-visibility.patch
hw/vendor/pulp_platform_fpnew.vendor.hjson
hw/vendor/pulp_platform_fpnew/src/fpnew_opgroup_multifmt_slice.sv

Patch to FPnew addressing questasim error (for simulation with reduced visibility)

fpnew: Fix tool issues with reduced simulation visibility

---

hw/ip/snitch_ssr/src/snitch_ssr_indirector.sv

This prevents index requests being revoked when an intersection is interrupted, instead waiting for the corresponding request to be issued and flushing the response.

sssr: Ensure lock-in when terminating intersection index stream

---

hw/ip/snitch/src/snitch.sv

Fixes issue https://github.com/pulp-platform/snitch/issues/442.

snitch: Correct decoding of `scfgri`

---

hw/ip/spm_interface/src/spm_1p_adv.sv

- Fixes ECC functionality.
- ECC functionality is still disabled.

spm: Fix ECC functionality

---

hw/system/occamy/fpga/README.md

Updated occamy/fpga/README.md for hero boot explanations

fpga: Updated readme

---

hw/system/snitch_cluster/sw/apps.list
hw/system/snitch_cluster/sw/apps/blas/gemm/Makefile
sw/blas/gemm/.gitignore
sw/blas/gemm/Makefile
sw/blas/gemm/data/datagen.py
sw/blas/gemm/data/params.hjson
sw/blas/gemm/src/gemm.h
sw/blas/gemm/src/main.c

Adapt `gemm` kernels to new `sw` structure

sw: Add gemm to blas folder
