pulp-platform/snitch

hw/ip/snitch/src/snitch_pkg.sv
hw/ip/snitch_cluster/src/snitch_cluster.sv
hw/ip/snitch_cluster/src/snitch_cluster_wrapper.sv.tpl
hw/system/snitch_cluster/test/testharness.sv

For Occamy (and other multi-cluster systems) we are going to finally need the wide slave port. Added by this PR.

snitch_cluster: Add wide slave port

---

hw/ip/snitch_dma/src/axi_dma_twod_ext.sv

Fixes an include required for the ``   `FF`` macro

dma: add missing include

---

sw/banshee/src/tran.rs

Fix the lifetime of a pointer to avoid access to a potentially deallocated CString.

banshee: Fix lifetime of CString pointer

---

.github/workflows/ci.yml

This PR adds testing of the `snRuntime` and `snBLAS` libraries on a freshly build `banshee`. The Docker container version is still tested (although this applies to the docker version that has been pushed for the previous commit.

ci: Run SW on CI built banshee

---

sw/banshee/src/engine.rs

The `wfi` vector storing which core has a pending wake-up request did not consider the `base-hartid`. This led to out-of-bound array accesses if `base-hartid > 0`.
This should fix the failing CI.

banshee: Consider the hartid offset in the `wfi` implementation

---

hw/ip/snitch/src/snitch.sv
hw/ip/snitch_icache/src/snitch_icache_l0.sv

This PR addresses the implicit assumption in Snitch, that the instruction interface has to be stable once the instruction is ready. Snitch will violate the protocol at the output interface otherwise. 
For example, when we execute a load but the memory interface is not ready, Snitch will already have enabled the valid signal and has to hold this signal until it gets a ready. However, the current cache policy might replace the cache line holding this load instruction with the prefetched line, which would lead to the cache withdrawing the ready signal. This leads to Snitch violating the protocol on the memory interface.
This PR addresses this issue with:
- Updated cache eviction policy to make the interface stable.
- Added assertion in Snitch, checking for a stable instruction interface.
A …

Skip the cache line currently used in the eviction policy

---

sw/banshee/src/riscv.rs
sw/banshee/src/tran.rs
sw/vendor/riscv-opcodes/parse-opcodes

`rust-analyzer` currently complains the enums and structs do not follow the naming convention. A small change in `riscv-opcodes` fixes this.

banshee: Align the code with `rust-analyzer` suggestions

---

hw/ip/snitch_cluster/src/snitch_cc.sv
hw/ip/snitch_cluster/src/snitch_ssr_streamer.sv

Configuring the SSR with the `scfgwi` instructions as [described in the documentation](https://github.com/pulp-platform/snitch/blob/master/docs/rm/custom_instructions.md#configuration-register-operations) is not working due to a wrong unpacking of `dm` and `reg` fields.
With these changes, the `scfgwi` instruction is correctly decoded according to this table
| imm[11:4] | imm[4:0] | rs1   | funct3 | rd    | opcode     | operation |
|:---------:|:--------:|:-----:|:------:|:-----:|:----------:|:---------:|
| 7         | 5        | 5     | 3      | 5     | 7          |           |
| reg       | ssr      | value | 010    | 00000 | OP-CUSTOM1 | SCFGWI    |
The immediate read `scfgri` doesn't work either. The problem here is that the `mem_resp_valid_i` signal is asserted a clock cycle delayed …

ssr: Unpacking of SSR address according to ISA documentation

---

sw/banshee/src/tran.rs

Fixing a typo as left-over from #73

banshee: Fix comment typo in ssr instruction parsing

---

docs/rm/custom_instructions.md

A minor fix in the documentation related to issue #68. The indices in the immediate were overlapping. The issue was fixed in #70, #73, and #75, but the documentation not updated.

docs: Fix `scfgr/w`'s immediate index

---

hw/ip/tcdm_interface/src/tcdm_interface.sv

In their current implementation, SSRs may violate the assertion in `hw/ip/tcdm_interface/tcdm_interface.sv:108` when their IO timings are nonzero.
This assertion checks that the request TCDM payload remains stable as long as it is valid, but the downstream is not yet ready. This includes write data, even if the request is a read.
However, SSRs directly connect the request write data to the bidirectional FIFO output and assert a request valid as long as an address is ready and there are credits. Since the cycle delay at which the FIFO changes its head contents is decoupled from the application delay of the ready signal at the IO interface, the lock-in assertion may be violated.
This PR masks the write data to `'0` on read, ensuring request stability on reads and writes with some logic …

tcdm-interface: Do not assert stable write data and strobe on reads

---

hw/ip/snitch/src/snitch.sv

Temporary "fix" for #72. I'll open an issue for a permanent fix.

snitch: Assert stability only stable on cacheable

---

hw/ip/snitch_icache/src/snitch_icache_l0.sv

If we have multiple early hits, the [instruction data](https://github.com/pulp-platform/snitch/blob/master/hw/ip/snitch_icache/src/snitch_icache_l0.sv#L166) will be garbage. Therefore, the prefetcher might calculate a garbage address and create a fetch to invalid memory. This PR disables the prefetcher when we have multiple early hits.
Alternatively, we could also modify the prediction logic to not try to predict the branch but just prefetch the next block. E.g. setting [`is_branch_taken` & `is_jal`](https://github.com/pulp-platform/snitch/blob/master/hw/ip/snitch_icache/src/snitch_icache_l0.sv#L290) to zero. This might be the better option,  but I would appreciate your opinion.

snitch_icache: Disable the prefetcher if there are multiple hits

---

hw/ip/snitch_cluster/src/snitch_cluster_wrapper.sv.tpl
hw/system/occamy/src/occamy_cluster_cfg.hjson
hw/system/occamy/src/occamy_cluster_wrapper.sv
hw/system/snitch_cluster/cfg/cluster.default.hjson

The generated cluster wrappers currently have inconsistent endianness for packed (flattened) and unpacked parameter arrays. 
Additionally, the existing cluster config files suggest little-endian hive and core lists, but the parsing scripts iterate through them in regular big-endian fashion.
This PR ensures consistency and correct wrappers by changing endianness in the existing configs to big-endian and reversing flattened parameter arrays.

cluster-cfg: Consistent endianness in config, script, and template

---

util/Makefrag

Catch the `no matches` error of `ls` when including the Makefrag in a directory without any trace files.

util/Makefrag: Catch failing dependency resolution

---

sw/banshee/Cargo.toml
sw/banshee/src/engine.rs

Allows to `--trace` at the same time as observing the output of the fake uart. Additionally, all printed lines are prepended with the source-hard-id

banshee: Fake uart to stderr with formatting and hartid

---

sw/banshee/src/engine.rs

As described in #105, if a non-zero TCDM base is used, the memory initialization breaks

banshee: Fix tcdm initialization by offsetting access

---

hw/ip/snitch_cluster/src/snitch_cc.sv
hw/ip/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral.sv
hw/ip/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral_reg.hjson
hw/ip/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral_reg_pkg.sv
hw/ip/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral_reg_top.sv
sw/snRuntime/src/start_cluster.c

Re-adds the wake-up register. Following the Mempool implementation. As I don't have any meaningful set-up to test the implementation I'd appreciate your feedback @noah95

snitch_cluster: Re-add `wake-up` register

---

hw/ip/test/src/tb_memory_axi.sv

Transaction issued by the DMA larger than 4K might deadlock. Increasing the transaction buffer fixes this in my case.
@zarubaf @accuminium do you think we can leave it like that for now?

testbench: Increase DMA memory transactions to omit DMA deadlock

---

hw/vendor/patches/pulp_platform_riscv_dbg/0002-Update-DMI-with-BSCANE2.patch
hw/vendor/pulp_platform_riscv_dbg.lock.hjson
hw/vendor/pulp_platform_riscv_dbg/debug_rom/debug_rom.sv
hw/vendor/pulp_platform_riscv_dbg/debug_rom/debug_rom_one_scratch.sv
hw/vendor/pulp_platform_riscv_dbg/debug_rom/gen_rom.py
hw/vendor/pulp_platform_riscv_dbg/src/dm_csrs.sv
hw/vendor/pulp_platform_riscv_dbg/src/dm_mem.sv
hw/vendor/pulp_platform_riscv_dbg/src/dm_obi_top.sv
hw/vendor/pulp_platform_riscv_dbg/src/dm_pkg.sv
hw/vendor/pulp_platform_riscv_dbg/src/dm_sba.sv
hw/vendor/pulp_platform_riscv_dbg/src/dmi_bscane_tap.sv
hw/vendor/pulp_platform_riscv_dbg/src/dmi_intf.sv
hw/vendor/pulp_platform_riscv_dbg/src/dmi_jtag.sv
hw/vendor/pulp_platform_riscv_dbg/src/dmi_jtag_tap.sv
hw/vendor/pulp_platform_riscv_dbg/src/dmi_test.sv

That bumps the debug module and adds the BSCANE2 fix which currently lives in a pull request towards `riscv-dbg` (https://github.com/pulp-platform/riscv-dbg/pull/111).

Update RISC-V Debug Module

---

hw/system/occamy/fpga/.gitignore
hw/system/occamy/fpga/vcu128.cfg
hw/system/occamy/fpga/vivado_ips/Makefile
hw/vendor/patches/pulp_platform_riscv_dbg/0003-riscv-dbg-Update-Bender.yml.patch
hw/vendor/pulp_platform_riscv_dbg/Bender.yml

This commit uses the `bscane_tap` from the `riscv-dbg` module to
faciliate debugging with OpenOCD.
The TAP is correctly identified on the VCU128 but the debugger is not
able to halt the core. Imho, this is due to the missing bootrom which
will just hang the FPGA.
Unfortunately, using the BSCANE2 primitives has the drawback of that the
Xilinx HW Server can not be connected at the same time (resource
conflict on the USB interface). That in turn means, that debugging with
GDB and ILA is mutual exclusive.
That is the current output I can produce with `OpenOCD` when connecting:
```
~$ openocd -f vcu128.cfg
Open On-Chip Debugger 0.11.0+dev-00117-gab337d05f-dirty
(2021-04-28-09:46)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter …
```

Use BSCANE2 tap for FPGA interaction

---

sw/banshee/src/runtime/jit.rs

The ssr configuration instruction was writing the repeat value to the `repeat_count` field instead of `repeat_bound`. This enables now to use the SSR repeat feature

banshee: Fix wrong ssr repeat assignment

---

hw/system/occamy/fpga/Makefile
hw/system/occamy/fpga/occamy_vcu128.tcl
hw/system/occamy/fpga/occamy_vcu128_bd.tcl
hw/system/occamy/fpga/vivado_ips/Makefile
hw/system/occamy/fpga/vivado_ips/occamy_xilinx.tcl

The current ILA is pretty large, also because it probes an AXI bus with a 512 bit data width. Often, the ILA is not needed or usable, e.g. when the JTAG port is occupied by the debugger. Excluding the ILA accelerates compile time by ~1h and reduces BRAM usage by ~40%.
This excludes the ILA per default. It can be included using the `make` variable `DEBUG` (e.g. `make fpga DEBUG=1`).

occamy/fpga: Make ILA excludable

---

hw/system/occamy/src/occamy_top.sv
hw/system/occamy/src/occamy_top.sv.tpl

Big memory macros are usually slow, so better have them in the slow clock domain.

occamy: Move SPM to slow domain

---

hw/ip/snitch/src/snitch.sv
hw/ip/snitch_cluster/src/snitch_fp_ss.sv

X's have hunted us a couple of times already - this PR add assertions to check that we are not writing-back any X's on the floating or integer register file. That should at least track where we are introducing unknown values.

Add `known` assertion on regfile write port

---

.github/workflows/build-docker.yml
util/container/Dockerfile

The `build-docker` run can be triggered manually and the LLVM toolchain version manually specified. The default value is `latest` which will be translated to the most recent tag in [snitch-llvm](https://github.com/pulp-platform/snitch-llvm/releases/tag/12.0.0-snitch-0.1.0-rc1)

container: Add LLVM toolchain to the Snitch Docker container

---

hw/ip/snitch/src/snitch.sv
hw/ip/snitch_cluster/src/snitch_cc.sv

Two bugs in the RTL prevented the use of the `scfgr`/`scfgri` instructions
- A missing scoreboard connection to keep track of the destination register value
- Timing in the `stream_to_mem` converter. The SSR respond with the read value in the same cycle as the request is made. Previously, the `id` and `valid` signals were delayed a cycle but not the `data`. This change removes the delay such that the response comes in the same cycle as the request
This now allows SSR barriers such as 
```c
asm volatile(
"1: \n"
"scfgri t0, 0\n"        // reat status word
"srli   t0, t0, 31\n"   // extract done bit 31
"beqz   t0, 1b\n"       // repeat if done bit not set
::: "t0");
```
Is the timing ok like this or should we insert a cut on the response?

ssr: Fix missing scoreboard and wrong timin in config reads

---

hw/system/occamy/src/memories.json
hw/system/occamy/src/occamy_cfg.hjson
hw/system/occamy/src/occamy_cluster_wrapper.sv

FPU utilization is limited by instruction cache misses in some cases. Increasing the cacheline from 128bit to 256bit mitigates this issues to some extent.

Occamy: Increase cacheline size to 256 bit

---

hw/ip/spm_interface/.gitignore
hw/ip/spm_interface/Bender.yml
hw/ip/spm_interface/include/spm_interface/assign.svh
hw/ip/spm_interface/src/spm_interface.sv
hw/ip/spm_interface/src/spm_rmw_adapter.sv
hw/ip/spm_interface/src/spm_test.sv
hw/ip/spm_interface/test/tb_spm_rmw_adapter.sv

Read-modify-write adapter for byte-wise read and write accesses which addresses #152 . For byte-wise read accesses, the adapter just returns the masked data. For byte-wise write accesses, the adapter stalls the original request while performing a full-width read access followed by a masked modify and full-width write
The input and of the module consist of the following signals (the output signals are mirrored)
```sv 
// Request-side channel
input logic  mem_req_i,
output logic mem_gnt_o,
input        addr_t mem_addr_i,
input        data_t mem_wdata_i,
input        strb_t mem_strb_i,
input logic  mem_we_i,
output logic mem_rvalid_o,
output       data_t mem_rdata_o
```
The protocol currently takes the following assumptions:
1. A valid handshake occurs when `req` and `gnt` are high. 
2. The …

Add: Read-modify-write (RMW) module

---

hw/ip/snitch_ssr/src/snitch_ssr_addr_gen.sv
hw/ip/snitch_ssr/test/fixture_ssr.sv

This change fixes the register layout for iteration loops in the SSR configuration interface to 4 loops, even if less loops are instantiated; this ensures a consistent configuration layout no matter the parameterization.
The hardware itself remains parameterizable in the same way as before.

ssr: Fix register interface to maximum of 4 loops

---

hw/ip/future/Bender.yml
hw/ip/future/src/axi_to_mem_interleaved.sv
hw/ip/snitch_cluster/src/snitch_cluster.sv

This PR addresses  #176. The new `axi_to_mem` module prevents deadlocks by allowing reads to bypass writes and vice versa and should not have a negative impact on performance. It is not 100% guaranteed that this will solve all deadlock cases, hence support for serialization should be added in the future

Update axi_to_mem module to prevent deadlock

---

hw/ip/snitch/src/snitch.sv

This addresses issue #167 where a write to `x0` causes the assertion to fail

hw: Disable assertion on write to x0

---

hw/system/occamy/src/occamy_quadrant_s1.sv
hw/system/occamy/src/occamy_quadrant_s1.sv.tpl
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg.hjson
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg_pkg.sv
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg_top.sv
hw/system/occamy/src/occamy_top.sv
hw/system/occamy/src/occamy_top.sv.tpl

Since the clusters will start issuing AXI transactions when they boot, we want to safeguard AXI transactions since - in case a given cluster isn't performing correctly - lock up the entire system.
Isolation is controlled via the SoC control register in the top level.

occamy: Add isolation signals to S1 quadrants

---

python-requirements.txt

In `2.3.52` the binray name changed to `ec`. This fixes the version used to mitigate further CI lint problems

ci: Fix editorconfig-checker version

---

hw/ip/snitch_cluster/src/snitch_fp_ss.sv
hw/ip/snitch_cluster/src/snitch_fpu.sv

When the SSR redirect CSR (`0x7C0`) is toggled, inflight writes to SSR register addresses may not be written back correctly:
* On enable: inflight writes to regular registers will be directed to SSRs
* On disable: inflight writes to SSRs will be directed to regular registers
This can cause frustrating glitches, especially because SSRs which overrun their jobs may block the FP pipeline indefinitely.
This PR determines at decode whether an instruction writes back to an SSR instead and propagates this information through the FPU with an additional tag bit.
This should be very lightweight in terms of additional logic and ensure "precise" SSR toggling, i.e. that SSRs are accessed exactly as defined by the program flow regardless of execution timing.

fpss: Tag SSR writebacks to prevent CSR toggle glitches

---

hw/system/occamy/src/occamy_pkg.sv
hw/system/occamy/src/occamy_top.sv
hw/system/occamy/src/occamy_top.sv.tpl
util/occamygen.py

As discussed in #192 the missing wide to narrow connection makes it impossible for the Snitch clusters to fetch from the bootrom. This PR fixes that issue and should probably go before #192.

occamy: Provide wide to narrow connection

---

hw/ip/snitch/src/snitch_pkg.sv
hw/ip/snitch_cluster/src/snitch_cluster.sv
hw/ip/snitch_cluster/src/snitch_cluster_wrapper.sv.tpl
hw/ip/snitch_cluster/src/snitch_hive.sv
hw/ip/snitch_icache/src/snitch_icache_refill.sv
hw/system/occamy/src/occamy_cluster_wrapper.sv
hw/system/occamy/src/occamy_pkg.sv
hw/system/occamy/src/occamy_quadrant_s1.sv
hw/system/occamy/src/occamy_top.sv
util/occamygen.py

Now that we have the wide DMA port it (can) make sense to actually
perform icache refills from that port, this potentially cuts down the
re-fill latency a couple of cycles.
More importantly, in case there is a read-only cache on the wide
network, it makes use of the same.
(Based on #191)

Instruction cache at wide cluster port

---

hw/ip/snitch/src/snitch.sv
hw/ip/snitch/src/snitch_pkg.sv
hw/ip/snitch_cluster/src/snitch_cc.sv
util/gen_trace.py

This specific sequence of instructions
```assembly
1: csrrsi	a0, mstatus, 8 # enable interrupts
2: wfi
3: csrrci	a0, mstatus, 8 # disable interrupts
```
Causes the core to sleep after `2` but immediately afterwards clears the interrupt enable from instruction `3`. Not sure if this is the right fix but it works for this problem
Before
After

Fix CSR wfi

---

hw/ip/snitch/src/snitch.sv
hw/system/occamy/src/memories.json
hw/vendor/openhwgroup_cva6/src/util/instr_tracer.sv
hw/vendor/patches/openhwgroup_cva6/0007-occamy-Chip-simulation-fixes.patch
util/clustergen/occamy.py

Apparently, there is some kind of race condition in the `display` in VCS. I didn't yet have the time to properly debug this and suggest disabling this (since it is only a problem with the async triggered exceptions).

occamy: Chip simulation fixes

---

sw/snRuntime/tests/interrupt.c

Disable `printf` in the interrupt test to speed-up the CI

sw: Disable printf in interrupt test

---

sw/cmake/SnitchUtilities.cmake

This change causes stalling unit tests to fail after 3/30 minutes (banshee/RTL).

runtime: Cancel tests after timeout

---

hw/system/occamy/src/occamy_quadrant_s1.sv
hw/system/occamy/src/occamy_top.sv
util/solder/solder.axi_change_iw.sv.tpl

Use all IDs in the remapped space instead of a static 4. I'm not sure what the impact on HW complexity is, so please chip in!

solder: Make full use of target ID space in IWC

---

sw/cmake/SnitchUtilities.cmake

I think the 180s are a bit too optimistic for one of the tests. Let's double it, still better than 5h :-)

Increase Banshee timeout to 360s

---

sw/banshee/src/engine.rs

This fixes any `attempt to add with overflow` panicks when using `amoadd`. I asusme wrapping add is the correct behaviour?

banshee: Change amoadd to a wrapping addition

---

util/container/Dockerfile

The `snitch-llvm` repository moved to `llvm-project` which causes the container build to fail

docker: Change LLVM toolchain URL

---

hw/system/occamy/src/occamy_pkg.sv.tpl

Derive the number of clusters from `occamy_cfg.hjson`. This fixes port
mismatches for numbers of clusters different from the default value
(`4`)

occamy_pkg: Derive number of clusters from cfg

---

hw/ip/snitch_cluster/src/snitch_cc.sv

Seems that signal was undriven in the case of de-activated SSRs.

lint: Fix missing signals and tb lint problems

---

sw/banshee/src/main.rs

I propose to disable module and jit optimization since in most use-cases optimization takes longer than actual runtime.

banshee: Disable IR and JIT optimizations per default

---

hw/system/occamy/src/occamy_cfg.hjson
hw/system/occamy/src/occamy_cluster_wrapper.sv

Removes floating-point features from the datamover core in each Snitch Cluster of Occamy to agree with the default parameterization.

occamy: Correct parameterization of DM core

---

hw/system/occamy/src/memories.json
util/clustergen/occamy.py

`occamygen` was outdated, resulting in read-only cache SRAMs not being included in the generated `memories.json`. This PR fixes this.

occamy: Update generator to include read-only cache memories

---

hw/ip/snitch_ssr/src/snitch_ssr_addr_gen.sv
hw/ip/snitch_ssr/src/snitch_ssr_indirector.sv
hw/ip/snitch_ssr/src/snitch_ssr_streamer.sv

This fixes some errors and warnings reported by VCS due to SSRs during elaboration of Occamy.

ssr: VCS elaboration fixes

---

hw/system/occamy/src/occamy_xilinx.sv
hw/system/occamy/src/occamy_xilinx.sv.tpl

Fix a small typo in the port assignment of `i_occamy`.

occamy_xilinx: Fix port assignment

---

hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg.hjson
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg.hjson.tpl
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg_top.sv

Currently, the default read-only cache address regions cause a fatal assertion failure on simulation. This assertion is unfortunately worded, but valid, as the address decoder used is not designed for address ranges of size 0 or smaller and spews further assertion failures if the former is circumvented.
This MR sets sensible default values for the SoC registers setting the address rules: each rule is set to a 32-bit block continuously addressed from 0 on reset. this should not be an issue, as the cache is bypassed by default.
This could be improved upon with configurable default address ranges, but this might be overkill and needs further configuration validation.

soc-regs: Stagger ro-cache reset regions to avoid illegal address rules

---

hw/system/occamy/src/memories.json
util/clustergen/occamy.py

The CVA6 memories declared in `occamygen.py` still reflected the write-through data cache configuration; now, they declare the correct write-back memories.

occamy: Update CVA6 memories to write-back migration

---

hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg.hjson
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg.hjson.tpl
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg_pkg.sv
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg_top.sv

This ensures that all S1 quadrants have all of their master and slave ports isolated on reset by changing the respective SoC registers' reset values.

occamy: Isolate all S1 quadrants by default

---

hw/ip/snitch_read_only_cache/Bender.yml

The read-only cache's Bender manifest contains wrong paths and is missing a dependency on `common_cells`. This currently causes no issues, but we could eventually trip over this as we did with `reqrsp_interface`.

ro-cache: Fix Bender manifest dependencies

---

hw/system/occamy/src/occamy_pkg.sv
hw/system/occamy/src/occamy_quadrant_s1.sv
hw/system/occamy/src/occamy_quadrant_s1.sv.tpl
hw/system/occamy/src/occamy_top.sv
hw/system/occamy/src/occamy_xilinx.sv
hw/system/occamy/test/testharness.sv
util/occamygen.py

Okay, here is my untested try to fix the mismatches. I've also added an assertion so that this doesn't happen again. Probably also wise to add the check to the other cluster ports.

occamy: Fix const cache mismatches

---

.github/workflows/lint.yml

As the workflow here is squash and merge we do not need to have a look at the commit messages to guarantee a linear history.

ci: Remove linting of history

---

.github/workflows/ci.yml
sw/banshee/README.md

Addressing #262
The `Get Banshee changed` job sets `banshee_changed` to `1` if there are any changes in `sw/banshee`. This re-builds banshee on pull requests that make changes to banshee. 
For workflows triggered on push, `github.event.pull_request.base.sha` is empty and banshee is not re-built

banshee: Build banshee in container if changed

---

sw/cmake/toolchain-llvm.cmake

Required by future LLVM toolchain that implements the smallfloat instructions

runtime: Enable experimental extensions in clang

---

.github/workflows/publish-docs.yml
docs/.gitignore
docs/doxybook2.json
mkdocs.yml
sw/.gitignore
sw/Doxyfile

Generate doxygen documentation in XML format, convert XML to Markdown using [doxybook2](https://github.com/matusnovak/doxybook2) and include in the published mkdocs documentation on gh-pages.
[This run](https://github.com/pulp-platform/snitch/actions/runs/1277244190) was triggered on a debug-commit and once merged, it *should* work on the regular doc-CI ;)

doc: Gen doxygen from runtime and include in mkdocs

---

docs/ug/snitch_cluster.md
hw/ip/test/src/sim.hh
hw/ip/test/src/verilator_lib.cc
hw/system/snitch_cluster/Makefile
util/Makefrag
util/patches/riscv-isa-sim/fesrv.patch

The main issue for it not working out-of-the-box was the use of `ucontext` in the front-end server (fesvr). Accoring [to the Linux man page](https://linux.die.net/man/3/swapcontext), this cooperative scheduling technique is removed in *POSIX.1-2008* and POSIX threads are recommended. The patch takes care of that. 
Unfortunately, i couldn't notice significant speedup in either verilate- nor run-time. I will try to make the snitch cluster hierarchically compileable and multithreaded to see if that speeds up the compilation.
- Disable VCD output per default, can be enabled with `--vcd` when runnint `./bin/snitch_cluster.vlt`
- Distinct build location for `fesvr` from vsim and verilator since it might linked against different libraries which would break vsim/vlt simultaneous simulation
- For …

cluster: Verilator testbench with LLVM12

---

sw/banshee/flexfloat/src/lib.rs
sw/banshee/src/engine.rs
sw/banshee/src/runtime/jit.ll
sw/banshee/src/tran.rs

* Fixes `fcvt.s.h` instruction in banshee which was broken due to a `float` and `i32` mismatch.
* Adds `fmv.x.h` and `fmv.h.x` instructions

banshee: Fix `fcvt` + add `fmv` for half-floats

---

hw/ip/snitch/src/snitch_lsu.sv
hw/ip/snitch_cluster/src/snitch_cluster.sv
hw/vendor/pulp_platform_fpnew.lock.hjson
hw/vendor/pulp_platform_fpnew/src/fpnew_opgroup_multifmt_slice.sv
hw/vendor/pulp_platform_fpnew/src/fpnew_sdotp_multi_wrapper.sv

- fix a aux_data signal width
- fix parameter issues with VCS
- rename module `fpnew_dotp_wrapper` to `fpnew_sdotp_multi_wrapper`

FPnew update: bugfix and VCS compatibility

---

hw/system/occamy/src/memories.json
hw/system/occamy/src/occamy_cfg.hjson
hw/system/occamy/src/occamy_quadrant_s1.sv
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg.hjson
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg_pkg.sv
hw/system/occamy/src/occamy_soc_ctrl/occamy_soc_reg_top.sv
hw/system/occamy/src/occamy_top.sv

Increase the read-only cache's line width and the number of supported address regions.

Double the read-only cache's cache line width

---

hw/system/occamy/src/occamy_cfg.hjson
hw/system/snitch_cluster/cfg/cluster.default.hjson

I added the latency for FP16 FMA in the cfg files, which was missing and always set it to 1. 
The generated occamy cluster is the same, while I increase to 2 the number of pipeline registers for the snitch cluster (now matching the value for FP16ALT)

fpu: Add `lat_comp_fp16` to system configs explicitly

---

.github/CODEOWNERS

hope this solves the default reviewer assignment from @zarubaf to @paulsc96 which was intended by #292.

Codeowners: fix typo for main codeowner

---

hw/system/occamy/src/occamy_quadrant_s1.sv
hw/system/occamy/src/occamy_quadrant_s1.sv.tpl

This pull request adds AXI cuts for each quadrant AXI port to remove input to output paths.

occamy: Improve quadrant timing through cuts on IO paths

---

hw/ip/snitch/src/snitch_pkg.sv

The DMA xbar has the following inputs
```
wide_axi_mst_req[SDMAMst]  // from DMA
wide_axi_mst_req[SoCDMAIn] // from SoC (ingress)
wide_axi_mst_req[ICache+i] // for each I$
```
and the outputs
```
wide_axi_slv_req[TCDMDMA]   // to the TCDM
wide_axi_slv_req[SoCDMAOut] // to the SoC (egress)
```
The `ICache` member should be in the enum with all the DMA xbar slaves (`cluster_master_dma_e`). It gets assigned the same value hence this does not change any behavior, just clears things up.

snitch: Fix wrong enum member in DMA xbar

---

hw/ip/snitch_icache/src/snitch_icache.sv
hw/ip/snitch_icache/src/snitch_icache_lookup.sv

Two minor code improvements in the icache:
- Change a duplicated, hardcoded value into a parameter
- Fix the refill in the lookup for a cache with a single set. This is a performance bug where we ignored half of the refills in such a configuration. AFAIK, we always have at least two sets at the moment, so nothing should change.

icache: Code improvements

---

hw/system/occamy/src/occamy_soc.sv
hw/system/occamy/src/occamy_soc.sv.tpl

This PR increases the number of additional spill register cuts on SoC-level AXI links to the following configuration:
* HBI <-> (Wide-X, Quadrants): 6
* Wide-X <-> (Quadrants, HBM): 3
* Narrow-X <-> (Quadrants, Peripherals): 3
* Narrow-X <-> (CVA6, Scratchpad): 1

occamy: Add appropriate AXI cuts in SoC

---

.github/workflows/lint.yml

The CI check `Occamy` in `.github/workflows/lint.yml` ran the following commands:
```bash
make -C hw/system/occamy all
util/git-diff.py --error-msg "::error ::Found differences, run `make -C hw/system/occamy` all before committing."
```
The \` in the argument to the `git-diff.py` script caused the make command enclosed by \` `make -C hw/system/occamy` to be executed which broke the `git-diff.py` script.

ci: Fix unintended command execution in lint message

---

hw/ip/snitch_cluster/src/snitch_cluster_wrapper.sv.tpl
hw/system/occamy/src/occamy_cluster_wrapper.sv

Fix an assignment pattern in the cluster wrapper that was not supported by some tools

cluster: Fix memory region syntax in wrapper

---

hw/ip/snitch/src/snitch.sv
hw/ip/snitch/src/snitch_l0_tlb.sv
hw/ip/snitch_cluster/src/snitch_barrier.sv
hw/ip/snitch_cluster/src/snitch_cluster.sv
hw/ip/snitch_cluster/src/snitch_fp_ss.sv
hw/ip/snitch_cluster/src/snitch_sequencer.sv
hw/ip/snitch_cluster/src/tcdm_shim.sv
hw/ip/snitch_vm/src/snitch_ptw.sv

This ensures (hopefully) that all RTL in the repo, and particularly in the cluster, has a consistent reset style: asynchronous and (globally) active-low.
I would have preferred to verify the completeness of this in some analysis tool first, but since all of the changed registers need to be fixed anyways, we might as well merge this now and add any additional fixes later.

hw: Ensure consistent reset practices and strategy

---

sw/snRuntime/include/snrt.h
sw/snRuntime/src/team.c

Quoting the C11 standard: 
> "Any function with internal linkage can be an inline function. For a function with external linkage, the following restrictions apply: If a function is declared with an inline function specifier, then it shall also be defined in the same translation unit.". 
For performance reasons, inlining of small functions e.g. `snrt_hartid()` is desirable. This is only possible if the function definition is available in the translation unit which desires inlining.
We can achieve this by moving the function definitions into the library header.

snRuntime: Optimize function calls via internal linkage

---

util/container/Dockerfile

Addresses issue #326. The CI is constantly failing because it cannot build the Hardware due to the new bender release. The fix mentioned in #326 solves this issue for now.
I would suggest specifying the old bender version and keeping the issue open.

docker: Specify bender version `0.23.2`

---

sw/banshee/src/engine.rs
sw/banshee/src/tran.rs

In banshee, register values in the traces are always encoded as hex values. For floats, it makes sense to format it as such. This increases readability and makes debugging much easier, e.g., SSR streams. I also added support for printing SIMD vectors. The traces will look like this:
```
00000000 00000734 0000 80003648  x8:0011fee0 RA:0011fe90 x10=0011fd70    # lw      a0, -80(s0)
00000000 00000735 0000 8000364c  x10:0011fd70 RA:0011fd70 RA:0011fd74 f03=        0.000000  # fld     ft3, 0(a0)
00000000 00000736 0000 80003650  x10:0011fd70 RA:0011fd78 RA:0011fd7c f04=        0.000000  # fld     ft4, 8(a0)
00000000 00000737 0000 80003654  x10:0011fd70 RA:0011fd80 RA:0011fd84 f05=        0.000000  # fld     ft5, 16(a0)
00000000 00000738 0000 80003658  x23:0011fd50 RA:0011fd50 f06=     -0.4387 …
```

banshee: Emit float register values as float instead of hex

---

sw/banshee/config/mempool.yaml
sw/banshee/src/tran.rs

- Support `fence` instructions with correct ordering for reads and writes. Peripheral ordering is currently not supported.
- Update the MemPool configuration to match the current configuration system's requirements

banshee: Support the `fence` instruction

---

hw/ip/snitch_cluster/src/snitch_cc.sv
hw/ip/snitch_ssr/src/snitch_ssr.sv
hw/ip/snitch_ssr/src/snitch_ssr_addr_gen.sv
hw/ip/snitch_ssr/src/snitch_ssr_streamer.sv
hw/ip/snitch_ssr/test/fixture_ssr.sv
hw/ip/snitch_ssr/test/fixture_ssr_streamer.sv

Blocks writes to the SSR configuration registers while a shadowed job is pending by adding backpressure (`cfg_wready_o`).
This enables the safe, repeated issuing of SSR jobs without any integer-FP synchronization or SSR done polling: the core can run ahead in job scheduling and is stalled as needed to prevent overwriting pending jobs until they are issued.
Note that if a faulty sequence of jobs and register accesses is programmed, this may cause semantic deadlocks between the core and SSRs; however, such deadlocks can always occur in faulty programs using SSRs.

ssr: Add backpressure to config writes when job outstanding

---

hw/system/occamy/src/occamy_soc.sv
hw/system/occamy/src/occamy_soc.sv.tpl
util/solder/solder.axi_atop_filter.sv.tpl
util/solder/solder.py

* Remove ID serializer in front of SPM
* Move narrow-to-wide ID width conversion behind atomics adapter
* Add ATOP filters in front of all atomics-incapable narrow slaves

occamy: Preserve ID widths until atomic adapters, add ATOP filters

---

hw/system/occamy/src/occamy_soc.sv
util/solder/solder.axi_atop_filter.sv.tpl

The name of the ATOP filter instance is hardcoded which results in multiple instances that are called `i_axi_atop_filter ` which does not compile.
See for example `occamy_soc.sv`

solder: Parametrize ATOP template instance name

---

hw/system/occamy/src/occamy_soc.sv
hw/system/occamy/src/occamy_soc.sv.tpl

Add missing `i_` prefix on instance names of `axi_atop_filter`.
**Dependency:** first PR #351 should be merged.
Proposal: should we add the compilation of the occamy system to CI to prevent further mistakes like this?

occamy: Fix `axi_atop_filter` instantiation names

---

hw/vendor/openhwgroup_cva6/Bender.yml
hw/vendor/openhwgroup_cva6/include/std_cache_pkg.sv
hw/vendor/openhwgroup_cva6/src/axi_adapter.sv
hw/vendor/openhwgroup_cva6/src/cache_subsystem/miss_handler.sv
hw/vendor/patches/openhwgroup_cva6/0017-cva6-Forward-atomic-transactions-from-wb_dcache-to-A.patch

Patches CVA6 with the upstream changes from PRs [#777](https://github.com/openhwgroup/cva6/pull/777) and [#838](https://github.com/openhwgroup/cva6/pull/838).

cva6: Forward "atomic transactions" from wb_dcache to AXI

---

hw/system/occamy/src/occamy_pkg.sv
hw/system/occamy/src/occamy_soc.sv
hw/system/occamy/src/occamy_top.sv
util/occamygen.py

Adds a missing attachment in `occamygen` of HBM config xbar to Occamy's config xbar, making the latter accessible.

occamy: Add missing routes to HBM config crossbar

---

hw/ip/snitch_dma/src/axi_dma_twod_ext.sv

Currently 2D requests with num_repetitions=1 will cause an error in the
DMA, being improperly handled. This will handle 2D requests with
num_reps=1 as 1D requests.

dma: Properly handle 2D request with single repetition

---

hw/vendor/patches/pulp_platform_common_cells/0006-common_cells-Clearable-cdcs-126.patch
hw/vendor/patches/pulp_platform_riscv_dbg/0004-riscv-dbg-func-reset-and-glitch-prevention-123-doc-c.patch
hw/vendor/pulp_platform_common_cells/Bender.yml
hw/vendor/pulp_platform_common_cells/CHANGELOG.md
hw/vendor/pulp_platform_common_cells/src/cdc_2phase.sv
hw/vendor/pulp_platform_common_cells/src/cdc_2phase_clearable.sv
hw/vendor/pulp_platform_common_cells/src/cdc_4phase.sv
hw/vendor/pulp_platform_common_cells/src/cdc_fifo_2phase.sv
hw/vendor/pulp_platform_common_cells/src/cdc_fifo_gray.sv
hw/vendor/pulp_platform_common_cells/src/cdc_fifo_gray_clearable.sv
hw/vendor/pulp_platform_common_cells/src/cdc_reset_ctrlr.sv
hw/vendor/pulp_platform_common_cells/src/cdc_reset_ctrlr_pkg.sv
hw/vendor/pulp_platform_common_cells/src/sync.sv
hw/vendor/pulp_platform_common_cells/test/cdc_2phase_clearable_tb.sv
hw/vendor/pulp_platform_common_cells/test/cdc_fifo_clearable_tb.sv
hw/vendor/pulp_platform_riscv_dbg/Bender.yml
hw/vendor/pulp_platform_riscv_dbg/CHANGELOG.md
hw/vendor/pulp_platform_riscv_dbg/doc/debug-system.md
hw/vendor/pulp_platform_riscv_dbg/src/dmi_cdc.sv
hw/vendor/pulp_platform_riscv_dbg/src/dmi_intf.sv
hw/vendor/pulp_platform_riscv_dbg/src/dmi_jtag.sv
hw/vendor/pulp_platform_riscv_dbg/src/dmi_jtag_tap.sv

occamy: Update `riscv_dbg` to version with fixed reset issues

---

hw/system/occamy/src/occamy_top.sv
hw/system/occamy/src/occamy_top.sv.tpl

Connects `master_r_err_i` on the debug module to the error signal of the memory bus and ties `master_r_other_err_i` to zero, as we don't need an overriding error signal.

occamy: Connect new bus error ports of debug module

---

hw/vendor/pulp_platform_fpnew.lock.hjson
hw/vendor/pulp_platform_fpnew/src/fpnew_fma.sv
hw/vendor/pulp_platform_fpnew/src/fpnew_fma_multi.sv

vendor: Update FPnew
Fix bug in `fpnew_fma` and `fpnew_fma_multi` triggered by the fp8alt format. The `SHIFT_AMOUNT_WIDTH` parameter was not large enough to represent the maximum shift

vendor: Update `fpnew` to fix FMA bug

---

hw/ip/snitch/src/snitch.sv

Right now, Snitch connects the register file read ports directly to the accelerator interface, which can cause handshaked data to be unstable and corresponding assertions in (isochronous) spill registers to fail. This MR instead uses the masked `opa` and `opb` signals to avoid this issue and reduce switching at the interface.
In the process, we also found and fixed a decoder bug in the `DMSTAT` instruction, which was not correctly declaring its operand register.
This issue might be revisited depending on how much these elongated paths affect core timing.

snitch: Pass `op(a|b)` on accelerator interface as masked

---

hw/ip/snitch_cluster/src/snitch_cc.sv
hw/ip/snitch_dma/src/axi_dma_tc_snitch_fe.sv
hw/system/occamy/src/occamy_quadrant_s1_ctrl.sv
hw/system/occamy/src/occamy_quadrant_s1_ctrl.sv.tpl
hw/vendor/lowrisc_opentitan/spi_host/rtl/spi_host_fsm.sv
hw/vendor/patches/lowrisc_opentitan/spi_host/0003-spi_host-Fix-CSAAT-behavior-See-387.patch
hw/vendor/patches/pulp_platform_tech_cells_generic/0001-tc-Changes-for-local-usage.patch
hw/vendor/patches/pulp_platform_tech_cells_generic/0003-tc_generic-Include-sram-for-Verilator.patch
hw/vendor/pulp_platform_tech_cells_generic.lock.hjson
hw/vendor/pulp_platform_tech_cells_generic.vendor.hjson
hw/vendor/pulp_platform_tech_cells_generic/Bender.yml
hw/vendor/pulp_platform_tech_cells_generic/CHANGELOG.md
hw/vendor/pulp_platform_tech_cells_generic/README.md
hw/vendor/pulp_platform_tech_cells_generic/src/fpga/pad_functional_xilinx.sv
hw/vendor/pulp_platform_tech_cells_generic/src/fpga/tc_sram_xilinx.sv
hw/vendor/pulp_platform_tech_cells_generic/src/rtl/tc_clk.sv
hw/vendor/pulp_platform_tech_cells_generic/src/rtl/tc_sram.sv

* Fix some unintentional latches which may be optimized away
* Update `tech_cells_generic` to release with correct Bender rules
* Fix #387 
* Remove some stray comments

occamy: Various small RTL fixes and updates

---

hw/ip/reqrsp_interface/src/reqrsp_to_axi.sv
hw/ip/snitch_cluster/src/snitch_amo_shim.sv
sw/snRuntime/CMakeLists.txt
sw/snRuntime/tests/atomics.c

Currently, all interfaces that return store-conditional responses simply set the response data to 1. However, most memory interfaces are wider than 32 bits and, depending on the alignment, Snitch only sees a slice of the returned value. The result is that store-conditionals not aligned to the interface width are reported as successful, independent of their actual outcome.
This PR fixes the modules that issue/convert the responses by returning -1 instead of one to guarantee that a non-zero return code reaches Snitch independent of any alignment issues. The RISC-V spec specifies a zero return value on success and a non-zero on failure, so we are free to return -1.
I fixed the:
- `reqrsp_interface`, which handles the AXI interface
- `tcdm_amo_shim`, which handles the atomics for the TCDM …

snitch: Fix LR/SC responses

---

hw/system/occamy/src/occamy_quadrant_s1_ctrl/occamy_quadrant_s1_reg.hjson
hw/system/occamy/src/occamy_quadrant_s1_ctrl/occamy_quadrant_s1_reg.hjson.tpl
hw/system/occamy/src/occamy_quadrant_s1_ctrl/occamy_quadrant_s1_reg_top.sv

The reset value of the quadrant reset register was changed from 0 (asserted) to 1 (not asserted): This means that the internal quadrant logic will *not* enter reset when the global reset is asserted. It will, however, still be clock-gated when the global reset is asserted.
The AXI isolators are all reset with the *global* reset: this means that both `state_aw_q` and `state_ar_q` are reset to the state `Isolate` on global reset, ensuring that no outgoing requests can be valid towards the SoC and the no SoC requests will be forwarded to the inner quadrant. Since the inner quadrant is still clock-gated, this should ensure a stable inner quadrant state and no AXI channel handshakes with the inner quadrant until it is ungated, ensuring the opportunity to reset the inner quadrant first.

occamy: Do not assert quadrant reset on global reset

---

hw/ip/test/src/tb_memory_axi.sv
hw/system/occamy/src/occamy_soc.sv
hw/system/occamy/src/occamy_soc.sv.tpl
hw/vendor/patches/pulp_platform_axi_riscv_atomics/0001-axi_riscv_atomics-Remove-timeunit-in-testbench.patch
hw/vendor/patches/pulp_platform_common_cells/0006-common_cells-Patch-ID-queue-for-VCS.patch
hw/vendor/pulp_platform_axi_riscv_atomics.lock.hjson
hw/vendor/pulp_platform_axi_riscv_atomics.vendor.hjson
hw/vendor/pulp_platform_axi_riscv_atomics/.gitignore
hw/vendor/pulp_platform_axi_riscv_atomics/Bender.yml
hw/vendor/pulp_platform_axi_riscv_atomics/CHANGELOG.md
hw/vendor/pulp_platform_axi_riscv_atomics/scripts/compile_vsim.sh
hw/vendor/pulp_platform_axi_riscv_atomics/scripts/run_vsim.sh
hw/vendor/pulp_platform_axi_riscv_atomics/src/axi_res_tbl.sv
hw/vendor/pulp_platform_axi_riscv_atomics/src/axi_riscv_amos.sv
hw/vendor/pulp_platform_axi_riscv_atomics/src/axi_riscv_amos_wrap.sv
hw/vendor/pulp_platform_axi_riscv_atomics/src/axi_riscv_atomics.sv
hw/vendor/pulp_platform_axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv
hw/vendor/pulp_platform_axi_riscv_atomics/src/axi_riscv_lrsc.sv
hw/vendor/pulp_platform_axi_riscv_atomics/src_files.yml
hw/vendor/pulp_platform_axi_riscv_atomics/test/axi_riscv_atomics_synth.v
hw/vendor/pulp_platform_axi_riscv_atomics/test/axi_riscv_atomics_tb.sv
hw/vendor/pulp_platform_axi_riscv_atomics/test/axi_riscv_atomics_tb_wave.do
hw/vendor/pulp_platform_axi_riscv_atomics/test/axi_riscv_lrsc_synth.v
hw/vendor/pulp_platform_axi_riscv_atomics/test/axi_riscv_lrsc_tb.sv
hw/vendor/pulp_platform_axi_riscv_atomics/test/axi_riscv_lrsc_tb_wave.do
hw/vendor/pulp_platform_axi_riscv_atomics/test/golden_memory.sv
hw/vendor/pulp_platform_axi_riscv_atomics/test/tb_axi_pkg.sv
hw/vendor/pulp_platform_common_cells/src/id_queue.sv
util/solder/solder.axi_atomic_adapter.sv.tpl
util/solder/solder.py

This PR updates the ATUN to the latest version.
- Guarantees atomicity by tracking downstream writes (limits number of writes in-flight and needs to be configured according to the performance requirements)
- Adds the option to use the USER signal to distinguish different harts. This is currently still disabled.
To make it work with VCS, we need to following two updates to dependencies:

axi-riscv-atomics: Update to latest version

---

hw/vendor/openhwgroup_cva6/src/ariane.sv
hw/vendor/openhwgroup_cva6/src/cache_subsystem/cache_ctrl.sv
hw/vendor/openhwgroup_cva6/src/cache_subsystem/cva6_icache.sv
hw/vendor/openhwgroup_cva6/src/cache_subsystem/cva6_icache_axi_wrapper.sv
hw/vendor/openhwgroup_cva6/src/cache_subsystem/std_cache_subsystem.sv
hw/vendor/openhwgroup_cva6/src/cache_subsystem/std_nbdcache.sv
hw/vendor/openhwgroup_cva6/src/cache_subsystem/wt_cache_subsystem.sv
hw/vendor/openhwgroup_cva6/src/controller.sv
hw/vendor/patches/openhwgroup_cva6/0009-cva6-Add-temporal-fence.patch
hw/vendor/patches/openhwgroup_cva6/0019-ariane-Latch-fence.t-to-avoid-glitches.patch

Fix a deadlock hazard when executing `fence.t` by stalling the icache to prevent new memory requests while draining.
ToDo:

cva6: Stall icache during `fence.t`

---

util/Makefrag

Fixes `work-vsim/compile.sh` script when compiling VHDL sources with VCS.

Makefrag: Switch to 64-bit version of vhdlan

---

hw/vendor/patches/pulp_platform_riscv_dbg/0001-riscv-dbg-Add-read_dmi_exp_backoff-function.patch
hw/vendor/pulp_platform_riscv_dbg/src/dm_pkg.sv
hw/vendor/pulp_platform_riscv_dbg/tb/jtag_dmi/jtag_test.sv

Provides a more robust alternative to read_dmi(), which does not rely
on a fixed delay, but rather calls read_dmi() until the read is successful
and automatically adjusts the delay with an exponential backoff scheme.

riscv-dbg: Add patch with `read_dmi_exp_backoff` function

---

sw/snRuntime/src/ssr.c

The previous FPU fence did not synchronize the integer and the FPU lane correctly. The single `fmv.x.w` instruction placed the integer register in the scoreboard but doesn't prevent integer instructions that don't use this register from being executed. Adding an additional integer `mv` instruction on this register should solve the problem.

sw: Fix `fpu_fence`

---

sw/banshee/config/multi_cluster_periph.yaml
sw/banshee/src/engine.rs
sw/banshee/src/tran.rs

This PR adds mainly two features:
- Create warnings when accessing memory that is not defined in the memory map of the config. This allows us to immediately see bugs in software related to the memory map.
- Do not emit an error if we have zeros in the text section. This usually happens because of padding and is not problematic at all.
All of this works nicely for MemPool. A few Banshee tests have accesses outside the memory map and create warnings now. It might be worth investigating them in the future as this hints that either Banshee is not configured correctly or missing a feature. I fixed the address map of the `multi_cluster_periph` config to match its tests. 
- `spmm_issr_frep`
- `multi_cluster`
- `dummy`

banshee: Improve error messages

---

hw/ip/test/src/SnitchSim.py
hw/ip/test/src/ipc.hh
hw/ip/test/src/tb_bin.cc
hw/system/snitch_cluster/SnitchSim.py

Adds an optional pipe-based IPC interface to `tb_bin`-based simulator binaries, as well as a Python class exemplifying how to use it. For now, this interface can read from, write to, and/or poll on the simulated memory, but this can be further extended.

test: Add pipe-based IPC control interface to `tb_bin`

---

.github/workflows/ci.yml
sw/banshee/build/runtime.rs
sw/banshee/flexfloat/src/lib.rs

The nightly version of Rust seems to enable opaque pointers per default. However, our current `llvm-sys` setup does not yet support those types. Since we need to fuse the IR generated by the Rust compiler with our own, generated with llvm-sys, we have to disable opaque pointers for the Rust compiler manually.
Simultaneously this fixes two minor style warnings.

banshee: Disable opaque pointers in JIT code

---

hw/ip/mem_interface/Bender.yml
hw/ip/tcdm_interface/Bender.yml
hw/ip/test/Bender.yml
hw/system/occamy/Bender.yml
hw/system/snitch_cluster/Bender.yml
hw/vendor/lowrisc_opentitan/gpio/Bender.yml
hw/vendor/lowrisc_opentitan/i2c/Bender.yml
hw/vendor/lowrisc_opentitan/rv_plic/Bender.yml
hw/vendor/lowrisc_opentitan/spi_host/Bender.yml
hw/vendor/patches/lowrisc_opentitan/gpio/0002-vendor-Correct-opentitan-peripheral-Bender-dependenc.patch
hw/vendor/patches/lowrisc_opentitan/i2c/0002-vendor-Correct-opentitan-peripheral-Bender-dependenc.patch
hw/vendor/patches/lowrisc_opentitan/rv_plic/0002-vendor-Correct-opentitan-peripheral-Bender-dependenc.patch
hw/vendor/patches/lowrisc_opentitan/spi_host/0005-vendor-Correct-opentitan-peripheral-Bender-dependenc.patch

Fix #326 by adding header dependencies in Bender manifests wherever they were missing. 
Also fix some Bender name mismatch warnings in the process.

hw: Fix Bender header dependencies

---

hw/system/occamy/fpga/Makefile
hw/system/occamy/fpga/README.md
hw/system/occamy/fpga/bootrom/Makefile

Follow the relocation of CVA6 SDK to OpenHW.

fpga: Change `ariane-sdk` to `cva6-sdk`

---

.github/workflows/ci.yml

CI takes the PULP LLVM compiler toolchain which is deployed to Sourceforge, unaware of the specific version which is deployed.
Therefore if the deployed compiler toolchain is broken, the CI consequently breaks.
This PR addresses this issue by taking a specific release of the toolchain from the Github repository.

ci: Get PULP LLVM compiler from fixed revision 0.12.0

---

.github/workflows/lint.yml

Fixes the Ubuntu version of the linting job to 18.04, which is guaranteed to ship clang-format-10

ci: Update as ubuntu-latest no longer ships clang-format-10

---

.github/workflows/lint.yml
util/trace/annotate.py

1. Correct bug when DWARF contains path discriminators
2. Generate diff file for neater visualization of trace-source correlation 
`addr2line` output can some time include [path discriminators](http://wiki.dwarfstd.org/index.php?title=Path_Discriminators). The output line containing the source file and line number could thus look like the following:
```
offload.c:46 (discriminator 1)
```
This PR fixes `annotate.py` to handle such output from `addr2line`.
Currently, the tool interleaves every assembly instruction in the trace with the corresponding source line (and a slim call stack). For cleaner visualization, we would like to display the source code next to, instead of interleaved with, the trace. We can reuse existing diff visualization tools (e.g. `kompare`) to achieve this goal. This …

annotate.py: Generate diff file for neater visualization of trace-source correlation

---

hw/ip/snitch_cluster/src/snitch_cc.sv

When examining the traces, the wrong register and data is specified for writeback from the accelerator interface. E.g.:
```
6615000    0x80000a74 dmstati t0, 2                  #; 
6618000                                              #; (acc) t4  <-- 0xfe029ee3
```
Which should in this case instead be:
```
6615000    0x80000a74 dmstati t0, 2                  #; 
6618000                                              #; (acc) t0  <-- 0
```
Indeed the tracer RTL dumps the wrong signals. This PR fixes this bug.

tracer: Correct accelerator writeback bug

---

sw/banshee/Cargo.toml
sw/banshee/src/dram_preload.rs
sw/banshee/src/main.rs

Add these flags to the banshee arguments: 
1. `--file-paths=<path-to-binaries>`  
2. `--mem-offsets=<memory-offsets>` 
The file paths are the paths to your dataset data, which should be in binary format. If you have multiple data files you can separate them by commas. In order to save them at a specific location of the main memory make sure you enter a start address (`mem_offset`) for every binary file. As before, it can be a comma-separated list. The user has to be aware of the memory layout and make sure that the offsets are big enough so that data does not get overwritten. There is currently no warnings supported if memory gets overwritten in DRAM.

Add DRAM preloading in banshee

---

util/container/README.md

Hi, this is my first pull request in this repo.
It adds some quite trivial lines to the readme of the container, saying that you should login before pulling from ghcr.io 
Otherwise GitHub seems to refuse pulling the image.
Thanks!
Best regards,
Josse

docs: Add login line to container readme

---

hw/ip/snitch_cluster/src/snitch_fp_ss.sv

Conversion operations of type `(v)fcvt.x.y` where `x` and `y` are float types do _not_ use two source registers; instead, `rs2` is a sub-op field. Misdeclaring `rs2` as a register read can cause incorrect execution and/or deadlocks inside SSR regions.

hw: Fix reg decode of in-FPSS conversions

---

util/Makefrag

This is required to include the configuration-dependent source files.

util/Makefrag: Add CVA6 config bender target for verilator

---

hw/system/snitch_cluster/cfg/cluster.hjson
sw/blas/axpy/data/datagen.py
sw/blas/axpy/src/axpy.h
sw/blas/axpy/src/main.c
sw/snRuntime/src/ssr.h

- Add SSR functions to the snRuntime
- Extend the AXPY test to use SSR+FREP

runtime: Add back SSR functions
